const fs=require('fs');const crypto=require('crypto');const {promisify}=require('util');const {Pool}=require('pg');
async function main(){const db=new Pool({connectionString:process.env.DATABASE_URL});const client=await db.connect();try{await client.query('BEGIN');await client.query(`
CREATE SCHEMA IF NOT EXISTS sfaxstore;
CREATE TABLE IF NOT EXISTS sfaxstore.auth_limits(bucket text PRIMARY KEY,attempts integer NOT NULL);
CREATE TABLE IF NOT EXISTS sfaxstore.users(id serial PRIMARY KEY,name text NOT NULL,email text NOT NULL UNIQUE,password_hash text NOT NULL,role text NOT NULL DEFAULT 'USER' CHECK(role IN ('USER','ADMIN')),active boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sfaxstore.sessions(token_hash text PRIMARY KEY,user_id integer NOT NULL REFERENCES sfaxstore.users(id) ON DELETE CASCADE,expires_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS sfaxstore.categories(id serial PRIMARY KEY,name text NOT NULL,description text NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS sfaxstore.products(id serial PRIMARY KEY,name text NOT NULL,description text NOT NULL,price numeric(10,2) NOT NULL CHECK(price>=0),stock integer NOT NULL CHECK(stock>=0),image_url text NOT NULL,category_id integer NOT NULL REFERENCES sfaxstore.categories(id),sold integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sfaxstore.orders(id serial PRIMARY KEY,user_id integer NOT NULL REFERENCES sfaxstore.users(id),total numeric(10,2) NOT NULL,status text NOT NULL DEFAULT 'PENDING',shipping jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS sfaxstore.order_items(id serial PRIMARY KEY,order_id integer NOT NULL REFERENCES sfaxstore.orders(id) ON DELETE CASCADE,product_id integer NOT NULL REFERENCES sfaxstore.products(id),quantity integer NOT NULL CHECK(quantity>0),unit_price numeric(10,2) NOT NULL);
CREATE TABLE IF NOT EXISTS sfaxstore.images(id uuid PRIMARY KEY,mime text NOT NULL,content bytea NOT NULL);
CREATE INDEX IF NOT EXISTS sfaxstore_orders_user ON sfaxstore.orders(user_id);
`);
const existing=await client.query('SELECT count(*) FROM sfaxstore.categories');if(Number(existing.rows[0].count)===0){const seed=fs.readFileSync('SfaxStore.Api/Data/SfaxStoreSeedData.cs','utf8');for(const m of seed.matchAll(/new Category \{ Id = (\d+), Name = "([^"]+)", Description = "([^"]+)"/g))await client.query('INSERT INTO sfaxstore.categories(id,name,description) VALUES($1,$2,$3)',[m[1],m[2],m[3]]);for(const m of seed.matchAll(/new Product \{ Id = (\d+), Name = "([^"]+)", Description = "([^"]+)", Price = (\d+), Stock = (\d+), ImageUrl = "([^"]+)", CategoryId = (\d+), CreatedAt = new DateTime\((\d+), (\d+), (\d+)\), Sold = (\d+)/g))await client.query('INSERT INTO sfaxstore.products(id,name,description,price,stock,image_url,category_id,created_at,sold) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[...m.slice(1,8),`${m[8]}-${m[9].padStart(2,'0')}-${m[10].padStart(2,'0')}`,m[11]]);for(const table of ['products','categories'])await client.query(`SELECT setval(pg_get_serial_sequence('sfaxstore.${table}','id'),(SELECT max(id) FROM sfaxstore.${table}))`);}
if(!(await client.query("SELECT id FROM sfaxstore.users WHERE role='ADMIN'")).rows.length){if(!process.env.ADMIN_PASSWORD)throw new Error('ADMIN_PASSWORD is required for initial setup');const salt=crypto.randomBytes(16).toString('hex');const hash=salt+':'+(await promisify(crypto.scrypt)(process.env.ADMIN_PASSWORD,salt,64)).toString('hex');await client.query("INSERT INTO sfaxstore.users(name,email,password_hash,role) VALUES('Admin SfaxStore',$1,$2,'ADMIN')",[process.env.ADMIN_EMAIL||'admin@sfaxstore.tn',hash]);}
await client.query('COMMIT');console.log('SfaxStore database initialized.');}catch(e){await client.query('ROLLBACK');console.error(e.message);process.exitCode=1;}finally{client.release();await db.end();}}
main();
